name: Run postman API Tests

on:
  push:
    branches:
     -'**'

jobs:
 api-test:
  runs-on : windows-latest

steps:
-name: checkout Repository
uses: actions/checkout@v3

-name:  Setup Node
 Uses:  actions/setup-node@v3
 with:
   node-version: 24

-name : Install Newman
 run: npm install -g newman

-name: Run Collection
 run: newman run collection.json
  