name: Run Postman API Test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  api-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Verify files available in runner
      - name: Show files
        run: |
          pwd
          ls -la
          find . -maxdepth 3 -type f

      # Install Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Install Newman
      - name: Install Newman
        run: npm install -g newman

      # Run Postman collection
      - name: Run Collection
        run: newman run ./collection.json -e Agyield UAT2.postman_environment.json
