# This is a basic workflow to help you get started with Actions



       name: Run Postman API Test

on:
  push:
    branches:
      - '**'

jobs:
  api-test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Newman
        run: npm install -g newman

      - name: Run Collection
        run: newman run collection.json
